// <auto-generated />
using System;
using Day5EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day5EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241212141137_InitialCreate6")]
    partial class InitialCreate6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day5EF.Models.Department", b =>
                {
                    b.Property<int>("dptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dptId"));

                    b.Property<string>("dptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("dptId");

                    b.ToTable("departments");

                    b.HasData(
                        new
                        {
                            dptId = 4,
                            dptName = "IT"
                        },
                        new
                        {
                            dptId = 5,
                            dptName = "HR"
                        });
                });

            modelBuilder.Entity("Day5EF.Models.Employees", b =>
                {
                    b.Property<int>("EmployeesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeesId"));

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Joindate")
                        .HasColumnType("date");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int>("dptId")
                        .HasColumnType("int");

                    b.HasKey("EmployeesId");

                    b.HasIndex("dptId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeesId = 1,
                            EmployeeName = "Suhail",
                            Joindate = new DateOnly(2023, 1, 1),
                            Salary = 500,
                            dptId = 1
                        },
                        new
                        {
                            EmployeesId = 2,
                            EmployeeName = "John",
                            Joindate = new DateOnly(2023, 2, 1),
                            Salary = 700,
                            dptId = 2
                        });
                });

            modelBuilder.Entity("Day5EF.Models.Employees", b =>
                {
                    b.HasOne("Day5EF.Models.Department", "department")
                        .WithMany("Employees")
                        .HasForeignKey("dptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("Day5EF.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
